version: '3.8'

services:
  nginx:
    container_name: reverse-proxy
    image: nginx:alpine
    ports:
      - "9000:9000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/root/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      sd_network:
        ipv4_address: 10.0.0.2

networks:
  sd_network:
      name: sd_sd_network
      external: true
