version: '3.4'
services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "123@qwe123"
    ports:
      - 6000:1433
    volumes:
      - ./data:/var/opt/mssql/data
    networks:
      cr_network:
        ipv4_address: 10.0.0.10

  cr.core.api:
    image: cr.core.api
    container_name: cr.core
    build:
      context: ../../BE
      dockerfile: Services/Core/CR.Core.API/Dockerfile
    ports:
      - 5001:8080
    configs:
      - source: appsettings
        target: /app/appsettings.json
    secrets:
      - source: public_key
        target: /app/public_key.${ASPNETCORE_ENVIRONMENT}.pem
      - source: private_key
        target: /app/private_key.${ASPNETCORE_ENVIRONMENT}.pem
    volumes:
      - ${PWD}/secrets/DataProtection-Keys:/app/DataProtection-Keys
    networks:
      cr_network:
        ipv4_address: 10.0.0.11

  minio:
    image: quay.io/minio/minio
    container_name: minio-manager
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=123qwe@123
    command: server --console-address ":9001" /data
    networks:
      cr_network:
        ipv4_address: 10.0.0.12

  seq:
    image: datalust/seq:latest
    container_name: cr.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    networks:
      cr_network:
        ipv4_address: 10.0.0.13

  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - 3001:3000

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "123@123abc"
    networks:
      cr_network:
        ipv4_address: 10.0.0.14

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123qwe
    networks:
      cr_network:
        ipv4_address: 10.0.0.15

configs:
  appsettings:
    file: ./configs/appsettings.json
    name: appsettings
  notification-env:
    file: ./configs/.env
    name: notification-env
secrets:
  public_key:
    file: ./secrets/public_key.${ASPNETCORE_ENVIRONMENT}.pem
  private_key:
    file: ./secrets/private_key.${ASPNETCORE_ENVIRONMENT}.pem

networks:
  cr_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.1/24
